#ifndef CMARK_VERSION_H
#define CMARK_VERSION_H

#define CMARK_VERSION_MAJOR 0
#define CMARK_VERSION_MINOR 30
#define CMARK_VERSION_PATCH 3

#define CMARK_VERSION_INT ((CMARK_VERSION_MAJOR << 16) | (CMARK_VERSION_MINOR << 8) | CMARK_VERSION_PATCH)

#define CMARK_VERSION "0.30.3"
#define CMARK_VERSION_STRING "0.30.3"

#endif
