#ifndef CMARK_CONFIG_H
#define CMARK_CONFIG_H

#define CMARK_VERSION_MAJOR 0
#define CMARK_VERSION_MINOR 30
#define CMARK_VERSION_PATCH 3
#define CMARK_VERSION_COMPILE 0

#define CMARK_VERSION "0.30.3"

#endif
