name: Run Tests

on:
  pull_request:
    branches:
      - 'master'
      - 'main'
      - 'releases/**'
  push:
    branches:
      - 'master'
      - 'main'
      - 'releases/**'

  jobs:
    test_features:

      runs-on: ubuntu-latest

      steps:
      - name: "Checkout the code"
        uses: actions/checkout@v4
      
      - name: "Run jest"
        uses: stefanoeb/jest-action@1.0.3
